# This is a basic workflow to help you get started with Actions

name: Parcial

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
            aws-region: us-east-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv env
          source env/bin/activate
          pip install zappa
          pip install -r requirements.txt
          pip list
      
      - name: Install Ruff
        run: pip install ruff

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .

      - name: test flake8
        run: |
          source env/bin/activate
          cd lambda_functions/download_lambda
          flake8 scrapping_pages.py
          cd ..
          cd processing_lambda
          flake8 processing_data.py

      - name: checkconnection
        run: |
          source env/bin/activate  
          aws s3 ls
          aws lambda list-functions


      - name: zappa deploy scraping
        run: |
          source env/bin/activate
          cd lambda_functions/download_lambda
          zappa update

      - name: zappa deploy processing
        run: |
          source env/bin/activate 
          cd lambda_functions/processing_lambda
          zappa update
  
  

      # - name: Test with pytest
      #   run: |
      #     pytest

          
